# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: format
        name: format
        entry: hatch fmt
        language: system
        pass_filenames: false
    -   id: mypy
        name: mypy
        entry: hatch run dev:mypy src
        language: system
        pass_filenames: false
    -   id: test
        name: test
        entry: hatch test
        language: system
        pass_filenames: false
